spruceid/treeldr

- README.md
> Missing commas in the README.

- modules/json-ld-context/Cargo.toml
- modules/json-ld-context/src/command.rs
- modules/json-ld-context/src/lib.rs
- modules/json-ld-context/tests/generate.rs
- modules/json-ld-context/tests/generate/e01.tldr
- modules/json-ld-context/tests/generate/t01-in.tldr
- modules/json-ld-context/tests/generate/t01-out.json
- modules/json-ld-context/tests/generate/t02-in.tldr
- modules/json-ld-context/tests/generate/t02-out.json
- modules/json-ld-context/tests/generate/t03-in.tldr
- modules/json-ld-context/tests/generate/t03-out.json
- modules/json-ld-context/tests/generate/t04-in.tldr
- modules/json-ld-context/tests/generate/t04-out.json
> Add tests to the JSON-LD context generator.

- syntax/src/build.rs
- syntax/tests/build/t001-out.nq
- syntax/tests/build/t002-out.nq
- syntax/tests/build/t015-out.nq
> Remove auto-labeling using doc comments first line.

- core/src/layout.rs
- core/src/layout/enumeration.rs
- core/src/lib.rs
- modules/json-ld-context/src/lib.rs
- modules/json-ld-context/tests/generate.rs
- modules/json-ld-context/tests/generate/t17-in.tldr
- modules/json-ld-context/tests/generate/t17-out.json
- modules/json-ld-context/tests/generate/t18-in.tldr
- modules/json-ld-context/tests/generate/t18-out.json
- modules/json-ld-context/tests/generate/t19-in.tldr
- modules/json-ld-context/tests/generate/t19-out.json
- modules/json-ld-context/tests/generate/t20-in.tldr
- modules/json-ld-context/tests/generate/t20-out.json
- syntax/src/build/intersection/enumeration.rs
> JSON-LD Context Generator: Generate `"@type": "@id"` when appropriate.

- build/Cargo.toml
- core/Cargo.toml
- modules/json-ld-context/Cargo.toml
- modules/rust/gen/Cargo.toml
> Make it work with stable Rust 1.65

- modules/json-ld-context/src/lib.rs
> JSON-LD Context Generator: Sort entries by name.

- modules/json-ld-context/src/lib.rs
> JSON-LD Context Generator: Iterative simplification

- build/src/layout/variant.rs
- core/src/name.rs
> Default name for reference variants.

- build/src/context/build.rs
- core/src/lib.rs
- modules/json-ld-context/src/command.rs
- modules/json-ld-context/src/lib.rs
- modules/json-ld-context/tests/generate.rs
- modules/json-ld-context/tests/generate/t21-in.tldr
- modules/json-ld-context/tests/generate/t21-out.json
Fixes #77
Added a regression test `t21`.
> JSON-LD Context Generator: Stack Overflow

- build/src/prop.rs
- core/src/prop.rs
> Allow multiple ranges for a property

- modules/json-ld-context/src/lib.rs
- modules/json-ld-context/tests/generate.rs
- modules/json-ld-context/tests/generate/t22-in.tldr
- modules/json-ld-context/tests/generate/t22-out.json
> JSON-LD Context Generator: Useless term definitions

- modules/json-ld-context/src/lib.rs
- modules/json-ld-context/tests/generate/t07-out.json
> Generate all type term definitions.

- modules/json-ld-context/src/command.rs
- modules/json-ld-context/src/lib.rs
- modules/json-ld-context/tests/generate.rs
- modules/json-ld-context/tests/generate/t23-in.tldr
- modules/json-ld-context/tests/generate/t23-out.json
- modules/json-ld-context/tests/generate/t24-in.tldr
- modules/json-ld-context/tests/generate/t24-out.json
- modules/json-ld-context/tests/generate/t25-in.tldr
- modules/json-ld-context/tests/generate/t25-out.json
> JSON-LD Context Generator: Flat context generation

- build/src/context/initialize/xsd.rs
- build/src/ty/datatype.rs
- core/src/node.rs
- core/src/prop.rs
- core/src/ty/data.rs
- modules/json-ld-context/src/lib.rs
- modules/json-ld-context/src/resolved/build.rs
- modules/json-ld-context/tests/generate_json_ld_context/n001.tldr
- modules/json-ld-context/tests/generate_json_ld_context/p001-in.tldr
- modules/json-ld-context/tests/generate_json_ld_context/p002-in.tldr
- modules/json-ld-context/tests/generate_json_ld_context/p003-in.tldr
- modules/json-ld-context/tests/generate_json_ld_context/p004-in.tldr
- modules/json-ld-context/tests/generate_json_ld_context/p005-in.tldr
- modules/json-ld-context/tests/generate_json_ld_context/p006-in.tldr
- modules/json-ld-context/tests/generate_json_ld_context/p007-in.tldr
- modules/json-ld-context/tests/generate_json_ld_context/p008-in.tldr
- modules/json-ld-context/tests/generate_json_ld_context/p009-in.tldr
- modules/json-ld-context/tests/generate_json_ld_context/p010-in.tldr
- modules/json-ld-context/tests/generate_json_ld_context/p011-in.tldr
- modules/json-ld-context/tests/generate_json_ld_context/p012-in.tldr
- modules/json-ld-context/tests/generate_json_ld_context/p013-in.tldr
- modules/json-ld-context/tests/generate_json_ld_context/p014-in.tldr
- modules/json-ld-context/tests/generate_json_ld_context/p015-in.tldr
Also:
- introduced the (partial) definition of more xsd datatypes.
- improved datatype compilation.
Fixes #95
> Fix IRI of primitive `"@type"` bindings.

- README.md
> Update link to TreeLDR user guide.

- Cargo.toml
- build/Cargo.toml
- build/src/context/build/unify.rs
- build/src/layout.rs
- core/Cargo.toml
- load/Cargo.toml
- modules/json-ld-context/Cargo.toml
- modules/json-schema/Cargo.toml
- modules/rust/gen/Cargo.toml
- modules/rust/macros/Cargo.toml
- modules/rust/prelude/Cargo.toml
- syntax/Cargo.toml
- tldrc/Cargo.toml
> Factorize metadata and dependencies

- Cargo.toml
- build/src/context/build.rs
- build/src/context/build/unify.rs
- syntax/Cargo.toml
- syntax/tests/build.rs
- syntax/tests/build/p012-out.nq
Optimized unification of non-recursive blank nodes.
Fixes #101
> Timothee-haudebourg/issue101

- build/src/context.rs
- build/src/context/build.rs
- build/src/context/build/minimize.rs
- core/src/multiple.rs
> Cleanup the `rdfs:domain` and `rdfs:range` relation.

- modules/rust/gen/src/syntax/tr_impl/rdf/from.rs
- modules/rust/gen/src/syntax/ty/primitive.rs
- modules/rust/gen/src/tr_impl/class.rs
- modules/rust/gen/src/tr_impl/rdf/from.rs
- modules/rust/gen/src/tr_impl/rdf/from/enum.rs
- modules/rust/gen/src/tr_impl/rdf/from/primitive.rs
- modules/rust/gen/src/tr_impl/rdf/from/struct.rs
- modules/rust/gen/src/ty.rs
- modules/rust/gen/src/ty/primitive/derived.rs
- modules/rust/prelude/src/rdf.rs
- modules/rust/prelude/src/rdf/from.rs
- modules/rust/prelude/src/rdf/from/literal.rs
- modules/rust/prelude/src/rdf/from/literal/xsd.rs
> Generate `rdf::FromLiteral` implementation for derived datatypes

- modules/json-ld-context/src/command.rs
> Add `standalone` option to the LD context generator.

- Cargo.toml
- layouts/src/format.rs
- layouts/src/layout.rs
- layouts/src/layout/list.rs
- layouts/src/layout/list/ordered.rs
- layouts/src/layout/list/sized.rs
- layouts/src/layout/list/unordered.rs
- layouts/src/layout/literal.rs
- layouts/src/layout/literal/data.rs
- layouts/src/layout/literal/id.rs
- layouts/src/layout/product.rs
- layouts/src/layout/sum.rs
- layouts/src/pattern.rs
- layouts/src/ref.rs
- layouts/src/utils/automaton.rs
> Add `Deserialize`/`Serialize` for compiled `Layout` enum.

- layouts/src/lib.rs
And also `IntoIterator` for `Layouts`.
> Impl `IntoIterator` for `&Layouts`

- layouts/src/format.rs
- layouts/src/layout.rs
- layouts/src/layout/list.rs
- layouts/src/layout/list/ordered.rs
- layouts/src/layout/list/sized.rs
- layouts/src/layout/list/unordered.rs
- layouts/src/layout/product.rs
- layouts/src/layout/sum.rs
> Provide a way to collect layouts dependencies.

- layouts/src/distill/de.rs
- layouts/src/distill/de/data.rs
- layouts/src/distill/hy.rs
- layouts/src/distill/hy/data.rs
- layouts/src/ref.rs
> Return proper error when a layout definition is not found.

- layouts/Cargo.toml
- layouts/src/value.rs
> Impl `TryFrom<Value>` for `serde_json::Value`
